fullnameOverride: mysql

image:
  repository: registry.hub.docker.com/library
  name: mariadb
  tag: 10.7.1
  pullPolicy: IfNotPresent
  args:
    - "--ignore-db-dir=lost+found"
ports:
  - containerPort: 3306

service:
  ports:
    - port: 3306

