# Required to make Spring Native generate the appropriate infrastructure for a separate management port, prometheus and K8S probes at build time
management.server.port: 9009
management.endpoint.health.probes.enabled: true
management.endpoints.web.exposure.include: health,info,prometheus
